#' Convert an OpenAlex JSON file to Parquet with abstract and citation
#'
#' This function combines `jq_execute()` and the Arrow package to convert an OpenAlex-style
#' JSON file containing a `results` array into a Parquet file. It reconstructs the abstract
#' and generates a citation for each entry, saving the result without loading full data into R.
#'
#' @param input_json_file Path to the OpenAlex JSON file
#' @param output_parquet_file Path to the output Parquet file
#' @param temp_jsonl Optional path for the temporary intermediate JSONL file (default: `tempfile()`) containing
#'   the `abstract` as well as the `citation` generated by `jq_execute()`
#' @param jq_path Path to the jq executable (default: "jq")
#'
#' @return Invisibly returns the path to the output Parquet file
#'
#' @md
#'
#' @importFrom arrow read_json_arrow write_parquet
#' @export
json_to_parquet <- function(
  input_json_file,
  output_parquet_file,
  temp_jsonl = tempfile(fileext = ".jsonl"),
  jq_path = "jq",
  page = NUL
) {
  jq_execute(input_json_file, temp_jsonl, jq_path = jq_path)

  tab <- arrow::read_json_arrow(temp_jsonl, as_data_frame = FALSE)
  arrow::write_parquet(tab, output_parquet_file)

  invisible(output_parquet_file)
}
